// ──────────────────────────────────────────────────────────────────────────
// Firebase Options — Generated by: flutterfire configure
//
// HOW TO FILL THIS IN (one-time setup):
//
// 1. Install the FlutterFire CLI:
//    dart pub global activate flutterfire_cli
//
// 2. Run from inside your flutter project folder:
//    flutterfire configure
//
// 3. That command will auto-fill ALL the values below from your Firebase
//    project and also create android/google-services.json and ios/GoogleService-Info.plist
//
// Until then, the placeholder values below allow the app to COMPILE but Firebase
// features (push notifications) will not work.
// ──────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run flutterfire configure to generate platform-specific options.',
        );
    }
  }

  // ── Web (Chrome / Edge) ──────────────────────────────────────────────────
  // Get these from Firebase Console → Project Settings → Your apps → Web app
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-WEB-API-KEY',
    appId: 'YOUR-WEB-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-FIREBASE-PROJECT-ID',
    authDomain: 'YOUR-FIREBASE-PROJECT-ID.firebaseapp.com',
    storageBucket: 'YOUR-FIREBASE-PROJECT-ID.firebasestorage.app',
    measurementId: 'YOUR-MEASUREMENT-ID',
  );

  // ── Android ──────────────────────────────────────────────────────────────
  // Get these from Firebase Console → Project Settings → Your apps → Android app
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-ANDROID-API-KEY',
    appId: 'YOUR-ANDROID-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-FIREBASE-PROJECT-ID',
    storageBucket: 'YOUR-FIREBASE-PROJECT-ID.firebasestorage.app',
  );

  // ── iOS ──────────────────────────────────────────────────────────────────
  // Get these from Firebase Console → Project Settings → Your apps → iOS app
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-IOS-API-KEY',
    appId: 'YOUR-IOS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-FIREBASE-PROJECT-ID',
    storageBucket: 'YOUR-FIREBASE-PROJECT-ID.firebasestorage.app',
    iosBundleId: 'com.example.grazetrackApp',
  );

  // ── macOS ─────────────────────────────────────────────────────────────────
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-MACOS-API-KEY',
    appId: 'YOUR-MACOS-APP-ID',
    messagingSenderId: 'YOUR-SENDER-ID',
    projectId: 'YOUR-FIREBASE-PROJECT-ID',
    storageBucket: 'YOUR-FIREBASE-PROJECT-ID.firebasestorage.app',
    iosBundleId: 'com.example.grazetrackApp',
  );
}
